import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{LayoutDashboard,Users,Mic2,Gift,Palette,Settings,LogOut,RefreshCw}from'lucide-react';
import'./style.css';
const db=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const nav=[['dashboard','الرئيسية',LayoutDashboard],['users','المستخدمون',Users],['rooms','الغرف',Mic2],['assets','الأصول',Palette],['gifts','الهدايا',Gift],['settings','الإعدادات',Settings]];
function Login(){const[e,setE]=useState(''),[p,setP]=useState(''),[m,setM]=useState('');async function go(){const{error}=await db.auth.signInWithPassword({email:e,password:p});if(error){setM(error.message);return}const{data}=await db.rpc('is_admin');if(!data){await db.auth.signOut();setM('الحساب لا يملك صلاحية الإدارة.')}}return <div className="login"><div className="login-card"><div className="logo">◉</div><h1>VoiceRoom Control Center</h1><input placeholder="البريد الإلكتروني" value={e} onChange={x=>setE(x.target.value)}/><input type="password" placeholder="كلمة المرور" value={p} onChange={x=>setP(x.target.value)}/><button className="primary" onClick={go}>تسجيل الدخول</button>{m&&<div className="notice">{m}</div>}</div></div>}
function App(){const[s,setS]=useState(null),[ready,setReady]=useState(false);useEffect(()=>{db.auth.getSession().then(({data})=>setS(data.session)).finally(()=>setReady(true));const{data}=db.auth.onAuthStateChange((_,v)=>setS(v));return()=>data.subscription.unsubscribe()},[]);if(!ready)return <div className="splash"><div><div className="logo">◉</div><h1>VoiceRoom</h1></div></div>;return s?<Console/>:<Login/>}
function Console(){const[sec,setSec]=useState('dashboard'),[tick,setTick]=useState(0);return <div className="app" dir="rtl"><aside><div className="brand"><div className="logo">◉</div><div><b>VoiceRoom</b><small>مركز التحكم</small></div></div><nav>{nav.map(([id,t,I])=><button className={sec===id?'active':''} key={id} onClick={()=>setSec(id)}><I size={18}/><span>{t}</span></button>)}</nav><button className="logout" onClick={()=>db.auth.signOut()}><LogOut size={18}/>تسجيل الخروج</button></aside><main><header><div><h2>{nav.find(x=>x[0]===sec)[1]}</h2><span>اتصال مباشر بقاعدة البيانات</span></div><button className="refresh" onClick={()=>setTick(x=>x+1)}><RefreshCw size={16}/>تحديث</button></header>{sec==='dashboard'?<Dashboard tick={tick}/>:<List table={sec==='users'?'profiles':sec==='rooms'?'rooms':sec==='assets'?'admin_control_assets':sec==='gifts'?'gifts':'admin_control_settings'} tick={tick}/>}</main></div>}
function Dashboard({tick}){const[c,setC]=useState({});useEffect(()=>{Promise.all(['profiles','rooms','gifts','admin_control_assets'].map(t=>db.from(t).select('id',{count:'exact',head:true}))).then(a=>setC({users:a[0].count||0,rooms:a[1].count||0,gifts:a[2].count||0,assets:a[3].count||0}))},[tick]);return <div className="content"><div className="stats"><div className="stat"><span>المستخدمون</span><strong>{c.users??'—'}</strong></div><div className="stat"><span>الغرف</span><strong>{c.rooms??'—'}</strong></div><div className="stat"><span>الهدايا</span><strong>{c.gifts??'—'}</strong></div><div className="stat"><span>الأصول</span><strong>{c.assets??'—'}</strong></div></div><div className="card"><h3>لوحة التحكم الجديدة</h3><p>إدارة مباشرة للمستخدمين والغرف والأصول والهدايا وإعدادات التطبيق.</p></div></div>}
function List({table,tick}){const[r,setR]=useState([]);useEffect(()=>{db.from(table).select('*').limit(100).then(({data})=>setR(data||[]))},[table,tick]);return <div className="content"><div className="card">{r.map((x,i)=><div className="row" key={x.id||i}><div className="grow"><b>{x.display_name||x.name_ar||x.name||x.title||x.id||'سجل'}</b><small>{x.public_id||x.code||x.version||''}</small></div></div>)}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);