const API="https://hgsfdkopbbwbtvsrbpoi.supabase.co/functions/v1/admin-control";
let token=sessionStorage.getItem("pharaoh_admin_token")||"";
let state={users:[],rooms:[],agencies:[],gifts:[],topups:[],reports:[],bans:[],settings:{},counts:{}};
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function api(action,extra={}){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","apikey":"sb_publishable_-4jjp6J2GLVPkv8AW95TZQ_DLOEIWOm",...(token?{Authorization:"Bearer "+token}:{})},body:JSON.stringify({action,...extra})});const j=await r.json().catch(()=>({error:"استجابة غير صالحة"}));if(!r.ok)throw Error(j.error||"حدث خطأ");return j}
function toast(s){const x=document.createElement("div");x.className="toast";x.textContent=s;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function closeModal(){$("#modal").classList.add("hidden")}
window.closeModal=closeModal;
async function load(){state=await api("dashboard");$("#usersBadge").textContent=state.counts.users;$("#roomsBadge").textContent=state.counts.rooms;$("#topupsBadge").textContent=state.counts.pendingTopups;$("#reportsBadge").textContent=state.counts.openReports;renderPage(document.querySelector("#nav button.active")?.dataset.page||"dashboard")}
function setContent(h){$("#content").innerHTML=h}
function renderPage(page){const titles={dashboard:"الرئيسية",users:"إدارة المستخدمين",rooms:"إدارة الغرف",agencies:"الوكالات",gifts:"الهدايا",topups:"الشحن والدفعات",reports:"البلاغات",bans:"الحظر",settings:"إعدادات التطبيق"};$("#pageTitle").textContent=titles[page]||page;({dashboard:dashboard,users:users,rooms:rooms,agencies:agencies,gifts:gifts,topups:topups,reports:reports,bans:bans,settings:settings}[page]||dashboard)()}
function dashboard(){setContent('<div class="cards">'+[['users','المستخدمون'],['rooms','الغرف'],['agencies','الوكالات'],['gifts','الهدايا'],['pendingTopups','طلبات شحن معلقة'],['openReports','بلاغات مفتوحة'],['activeBans','حظر نشط']].map(([k,l])=>'<div class="card"><small>'+l+'</small><div class="metric">'+(state.counts[k]??0)+'</div></div>').join('')+'</div><div class="grid2"><div class="section"><h3>حالة النظام</h3><p class="ok">● قاعدة البيانات متصلة</p><p class="muted">جميع تغييرات الإدارة تمر عبر Edge Function وتُسجل في سجل التدقيق.</p></div><div class="section"><h3>إجراءات سريعة</h3><div class="actions"><button class="primary" onclick="openCreateGift()">+ هدية</button><button class="ghost" onclick="navTo('users')">المستخدمون</button><button class="ghost" onclick="navTo('rooms')">الغرف</button></div></div></div>')}
function navTo(p){document.querySelector('[data-page="'+p+'"]').click()}
function users(){setContent('<div class="toolbar"><button class="primary" onclick="openCreateUser()">+ مستخدم</button><input id="userSearch" placeholder="بحث بالاسم أو ID أو الهاتف..." oninput="filterUsers()"><button class="ghost" onclick="load()">↻ تحديث</button></div><div class="table-wrap"><div class="table-title">المستخدمون</div><table><thead><tr><th>ID</th><th>الاسم</th><th>المستوى</th><th>VIP</th><th>Coins</th><th>Diamonds</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody id="usersBody"></tbody></table></div>');drawUsers(state.users)}
function filterUsers(){const q=$("#userSearch").value.toLowerCase();drawUsers(state.users.filter(u=>[u.public_id,u.display_name,u.username,u.phone].join(" ").toLowerCase().includes(q)))}
function drawUsers(arr){$("#usersBody").innerHTML=arr.length?arr.map(u=>'<tr><td>'+esc(u.public_id)+'</td><td><b>'+esc(u.display_name)+'</b><br><small class="muted">@'+esc(u.username)+'</small></td><td>'+u.level+'</td><td>VIP '+u.vip_level+'</td><td>'+u.coins+'</td><td>'+u.diamonds+'</td><td>'+(u.is_banned?'<span class="pill bad">محظور</span>':'<span class="pill ok">نشط</span>')+'</td><td><button class="mini" onclick="editUser('+JSON.stringify(u).replaceAll('"','&quot;')+')">تعديل</button><button class="mini '+(u.is_banned?'success':'danger')+'" onclick="toggleBan(\''+u.id+'\','+u.public_id+','+u.is_banned+')">'+(u.is_banned?'فك الحظر':'حظر')+'</button></td></tr>').join(""):'<tr><td colspan="8" class="empty">لا توجد بيانات</td></tr>'}
function editUser(u){$("#modalContent").innerHTML='<h3>تعديل المستخدم #'+esc(u.public_id)+'</h3><div class="form-grid">'+field("الاسم","display_name",u.display_name)+field("اسم المستخدم","username",u.username)+field("الهاتف","phone",u.phone)+field("الدولة","country_code",u.country_code)+field("المستوى","level",u.level,"number")+field("VIP","vip_level",u.vip_level,"number")+field("Coins","coins",u.coins,"number")+field("Diamonds","diamonds",u.diamonds,"number")+field("نبذة","bio",u.bio,"text","full")+'</div><div class="actions"><button class="primary" onclick="saveUser(\''+u.id+'\')">حفظ التغييرات</button></div>';$("#modal").classList.remove("hidden")}
function field(label,key,val,type="text",cls=""){return '<label class="'+cls+'">'+label+'<input id="f_'+key+'" type="'+type+'" value="'+esc(val)+'"></label>'}
function openCreateUser(){$("#modalContent").innerHTML='<h3>إنشاء مستخدم حقيقي</h3><div class="form-grid">'+field("الاسم","cu_name","مستخدم جديد")+field("اسم المستخدم","cu_username","user"+Date.now())+field("البريد الإلكتروني","cu_email","user"+Date.now()+"@pharaoh.local")+field("كلمة المرور","cu_password","Pharaoh@123456")+field("Coins","cu_coins","0","number")+field("Diamonds","cu_dia","0","number")+'</div><button class="primary" onclick="createUser()">إنشاء المستخدم</button>';$("#modal").classList.remove("hidden")}
async function createUser(){const j=await api("create_user",{email:$("#f_cu_email").value,password:$("#f_cu_password").value,profile:{display_name:$("#f_cu_name").value,username:$("#f_cu_username").value,coins:Number($("#f_cu_coins").value),diamonds:Number($("#f_cu_dia").value)}});closeModal();await load();toast("تم إنشاء المستخدم فعلياً");if(j.temporaryPassword)alert("كلمة المرور: "+j.temporaryPassword)}
async function saveUser(id){const patch={};["display_name","username","phone","country_code","level","vip_level","coins","diamonds","bio"].forEach(k=>{const v=$("#f_"+k).value;patch[k]=["level","vip_level","coins","diamonds"].includes(k)?Number(v):v});await api("update_user",{id,patch});closeModal();toast("تم حفظ المستخدم");await load()}
async function toggleBan(id,pid,banned){if(banned){await api("unban_user",{user_id:id,public_id:pid})}else{const reason=prompt("سبب الحظر","مخالفة قواعد الاستخدام");if(reason===null)return;const hours=prompt("مدة الحظر بالساعات (اتركها فارغة للحظر الدائم)","");await api("ban_user",{user_id:id,public_id:pid,reason,hours});}toast("تم تنفيذ الإجراء");await load()}
function rooms(){setContent('<div class="toolbar"><button class="primary" onclick="newRoom()">+ غرفة</button><input id="roomSearch" placeholder="بحث في الغرف..." oninput="filterRooms()"><button class="primary" onclick="newRoom()">+ غرفة</button></div><div class="table-wrap"><div class="table-title">الغرف</div><table><thead><tr><th>ID</th><th>الغرفة</th><th>المضيف</th><th>التصنيف</th><th>المستمعون</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody id="roomsBody"></tbody></table></div>');drawRooms(state.rooms)}
function filterRooms(){const q=$("#roomSearch").value.toLowerCase();drawRooms(state.rooms.filter(r=>JSON.stringify(r).toLowerCase().includes(q)))}
function drawRooms(arr){$("#roomsBody").innerHTML=arr.length?arr.map(r=>'<tr><td>'+esc(r.display_id||r.id)+'</td><td><b>'+esc(r.title)+'</b><br><small class="muted">'+esc(r.description)+'</small></td><td>'+esc(r.host_name)+'</td><td>'+esc(r.category)+'</td><td>'+r.listeners_count+'</td><td>'+(r.is_closed?'<span class="pill bad">مغلقة</span>':r.is_locked?'<span class="pill">مقفلة</span>':'<span class="pill ok">مفتوحة</span>')+'</td><td><button class="mini" onclick="editRoom('+JSON.stringify(r).replaceAll('"','&quot;')+')">تعديل</button><button class="mini danger" onclick="deleteRoom(\''+r.id+'\')">حذف</button></td></tr>').join(""):'<tr><td colspan="7" class="empty">لا توجد غرف في قاعدة بيانات لوحة التحكم</td></tr>'}
function editRoom(r){$("#modalContent").innerHTML='<h3>تعديل الغرفة</h3><div class="form-grid">'+field("العنوان","r_title",r.title)+field("التصنيف","r_category",r.category)+field("المضيف","r_host",r.host_name)+field("عدد المقاعد","r_seats",r.seat_count,"number")+field("الإعلان","r_ann",r.announcement,"text","full")+field("الوصف","r_desc",r.description,"text","full")+field("رابط الغلاف","r_cover",r.room_cover,"text","full")+'</div><div class="actions"><button class="primary" onclick="saveRoom(\''+r.id+'\')">حفظ</button><button class="ghost" onclick="toggleRoom(\''+r.id+'\', '+(!r.is_closed)+')">'+(r.is_closed?'فتح الغرفة':'إغلاق الغرفة')+'</button><button class="ghost" onclick="lockRoom(\''+r.id+'\', '+(!r.is_locked)+')">'+(r.is_locked?'فتح القفل':'قفل الغرفة')+'</button></div>';$("#modal").classList.remove("hidden")}
async function saveRoom(id){const patch={title:$("#f_r_title").value,category:$("#f_r_category").value,host_name:$("#f_r_host").value,seat_count:Number($("#f_r_seats").value),announcement:$("#f_r_ann").value,description:$("#f_r_desc").value,room_cover:$("#f_r_cover").value};await api("update_room",{id,patch});closeModal();toast("تم حفظ الغرفة");await load()}
async function toggleRoom(id,closed){await api("update_room",{id,patch:{is_closed:closed}});closeModal();await load();toast(closed?"تم إغلاق الغرفة":"تم فتح الغرفة")}
async function lockRoom(id,locked){await api("update_room",{id,patch:{is_locked:locked}});closeModal();await load();toast(locked?"تم قفل الغرفة":"تم فتح الغرفة")}
async function deleteRoom(id){if(!confirm("حذف الغرفة نهائياً؟"))return;await api("delete_room",{id});await load();toast("تم حذف الغرفة")}
function newRoom(){openCreateRoom()}
function openCreateRoom(){const opts=state.users.map(u=>'<option value="'+u.id+'">'+esc(u.display_name)+' #'+u.public_id+'</option>').join("");$("#modalContent").innerHTML='<h3>إنشاء غرفة حقيقية</h3><div class="form-grid">'+field("اسم الغرفة","cr_name","غرفة جديدة")+field("التصنيف","cr_cat","general")+field("الوصف","cr_desc","")+field("المقاعد","cr_seats","8","number")+'<label>المالك<select id="f_cr_owner">'+opts+'</select></label></div><button class="primary" onclick="createRoom()">إنشاء الغرفة</button>';$("#modal").classList.remove("hidden")}
async function createRoom(){await api("create_room",{room:{name:$("#f_cr_name").value,category:$("#f_cr_cat").value,description:$("#f_cr_desc").value,seat_count:Number($("#f_cr_seats").value),owner_id:$("#f_cr_owner").value||null}});closeModal();await load();toast("تم إنشاء الغرفة فعلياً")}
function agencies(){setContent('<div class="toolbar"><button class="primary" onclick="openCreateAgency()">+ وكالة</button></div><div class="table-wrap"><div class="table-title">الوكالات</div><table><thead><tr><th>ID</th><th>الاسم</th><th>الكود</th><th>المالك</th><th>العمولة</th><th>الأعضاء</th><th>الرصيد</th><th>إجراءات</th></tr></thead><tbody>'+state.agencies.map(a=>'<tr><td>'+esc(a.id)+'</td><td>'+esc(a.name)+'</td><td>'+esc(a.code)+'</td><td>'+esc(a.owner_name)+'</td><td>'+a.commission_percentage+'%</td><td>'+a.members_count+'</td><td>'+a.coins_balance+'</td><td><button class="mini" onclick="editAgency('+JSON.stringify(a).replaceAll('"','&quot;')+')">تعديل</button></td></tr>').join("")+'</tbody></table></div>')}
function editAgency(a){$("#modalContent").innerHTML='<h3>تعديل الوكالة</h3><div class="form-grid">'+field("الاسم","a_name",a.name)+field("الكود","a_code",a.code)+field("العمولة %","a_comm",a.commission_percentage,"number")+field("الرصيد","a_coins",a.coins_balance,"number")+field("المالك","a_owner",a.owner_name)+ '</div><button class="primary" onclick="saveAgency(\''+a.id+'\')">حفظ</button>';$("#modal").classList.remove("hidden")}
function openCreateAgency(){const opts=state.users.map(u=>'<option value="'+u.id+'">'+esc(u.display_name)+' #'+u.public_id+'</option>').join("");$("#modalContent").innerHTML='<h3>إنشاء وكالة</h3><div class="form-grid">'+field("اسم الوكالة","ca_name","وكالة جديدة")+field("الوصف","ca_desc","")+ '<label>المالك<select id="f_ca_owner">'+opts+'</select></label></div><button class="primary" onclick="createAgency()">إنشاء</button>';$("#modal").classList.remove("hidden")}
async function createAgency(){await api("create_agency",{agency:{name:$("#f_ca_name").value,description:$("#f_ca_desc").value,owner_id:$("#f_ca_owner").value}});closeModal();await load();toast("تم إنشاء الوكالة فعلياً")}
async function saveAgency(id){await api("update_agency",{id,patch:{name:$("#f_a_name").value,code:$("#f_a_code").value,commission_percentage:Number($("#f_a_comm").value),coins_balance:Number($("#f_a_coins").value),owner_name:$("#f_a_owner").value}});closeModal();await load();toast("تم حفظ الوكالة")}
function gifts(){setContent('<div class="toolbar"><button class="primary" onclick="openCreateGift()">+ إضافة هدية</button></div><div class="table-wrap"><div class="table-title">الهدايا</div><table><thead><tr><th>الاسم</th><th>الفئة</th><th>Coins</th><th>Diamonds</th><th>3D</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>'+state.gifts.map(g=>'<tr><td>'+esc(g.name_ar)+'</td><td>'+esc(g.category)+'</td><td>'+g.coins+'</td><td>'+g.diamonds+'</td><td>'+(g.is_3d?"نعم":"لا")+'</td><td>'+(g.data?.is_active===false?'<span class="bad">معطلة</span>':'<span class="ok">فعالة</span>')+'</td><td><button class="mini" onclick="editGift('+JSON.stringify(g).replaceAll('"','&quot;')+')">تعديل</button></td></tr>').join("")+'</tbody></table></div>')}
function openCreateGift(){const g={id:"",name_ar:"هدية جديدة",name_en:"New Gift",category:"all",coins:100,diamonds:0,is_3d:false,animation_type:"default",custom_image:""};editGift(g,true)}
function editGift(g,isNew=false){$("#modalContent").innerHTML='<h3>'+(isNew?"إضافة هدية":"تعديل هدية")+'</h3><div class="form-grid">'+field("الاسم العربي","g_name",g.name_ar)+field("الاسم الإنجليزي","g_en",g.name_en)+field("Coins","g_coins",g.coins,"number")+field("Diamonds","g_dia",g.diamonds,"number")+field("الفئة","g_cat",g.category)+field("الأنيميشن","g_anim",g.animation_type)+field("صورة","g_img",g.custom_image,"text","full")+'</div><button class="primary" onclick="saveGift(\''+g.id+'\','+isNew+')">حفظ</button>';$("#modal").classList.remove("hidden")}
async function saveGift(id,isNew){const patch={name_ar:$("#f_g_name").value,name_en:$("#f_g_en").value,coins:Number($("#f_g_coins").value),diamonds:Number($("#f_g_dia").value),category:$("#f_g_cat").value,animation_type:$("#f_g_anim").value,custom_image:$("#f_g_img").value};if(isNew){await api("update_gift",{id,patch:{...patch,data:{is_active:true}}})}else await api("update_gift",{id,patch});closeModal();await load();toast("تم حفظ الهدية")}
function topups(){setContent('<div class="table-wrap"><div class="table-title">طلبات الشحن</div><table><thead><tr><th>المستخدم</th><th>Coins</th><th>المبلغ</th><th>الطريقة</th><th>الحالة</th><th>التاريخ</th><th>إجراء</th></tr></thead><tbody>'+state.topups.map(t=>'<tr><td>'+esc(t.profiles?.display_name||t.user_id)+'</td><td>'+t.coins+'</td><td>'+t.amount_minor/100+' '+esc(t.currency)+'</td><td>'+esc(t.provider)+'</td><td>'+esc(t.status)+'</td><td>'+new Date(t.created_at).toLocaleString("ar-EG")+'</td><td>'+(t.status==="pending"?'<button class="mini success" onclick="reviewTopup(\''+t.id+'\',\'paid\')">قبول</button><button class="mini danger" onclick="reviewTopup(\''+t.id+'\',\'rejected\')">رفض</button>':"—")+'</td></tr>').join("")+'</tbody></table></div>')}
async function reviewTopup(id,status){const note=prompt("ملاحظة","");await api("review_topup",{id,status,note});await load();toast("تم تحديث طلب الشحن")}
function reports(){setContent('<div class="table-wrap"><div class="table-title">البلاغات</div><table><thead><tr><th>ID</th><th>المبلغ عنه</th><th>الغرفة</th><th>السبب</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>'+state.reports.map(r=>'<tr><td>'+esc(r.id)+'</td><td>'+esc(r.target_user_id)+'</td><td>'+esc(r.room_id||"—")+'</td><td>'+esc(r.reason)+'</td><td>'+esc(r.status)+'</td><td>'+(r.status==="open"?'<button class="mini success" onclick="resolveReport(\''+r.id+'\',\'resolved\')">حل البلاغ</button><button class="mini" onclick="resolveReport(\''+r.id+'\',\'rejected\')">رفض</button>':"—")+'</td></tr>').join("")+'</tbody></table></div>')}
async function resolveReport(id,status){await api("resolve_report",{id,status});await load();toast("تم تحديث البلاغ")}
function bans(){setContent('<div class="table-wrap"><div class="table-title">سجل الحظر</div><table><thead><tr><th>Public ID</th><th>النوع</th><th>السبب</th><th>ينتهي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>'+state.bans.map(b=>'<tr><td>'+b.public_id+'</td><td>'+esc(b.ban_type)+'</td><td>'+esc(b.reason)+'</td><td>'+ (b.expires_at?new Date(b.expires_at).toLocaleString("ar-EG"):"دائم")+'</td><td>'+(b.active?'<span class="bad">نشط</span>':'منتهي')+'</td><td><button class="mini success" onclick="quickUnban('+b.public_id+')">فك الحظر</button></td></tr>').join("")+'</tbody></table></div>')}
async function quickUnban(pid){await api("unban_user",{public_id:pid});await load();toast("تم فك الحظر")}
function settings(){const s=state.settings||{};setContent('<div class="section"><h3>إعدادات التطبيق</h3><label>وضع الصيانة<select id="set_maint"><option value="false">متوقف</option><option value="true">مفعل</option></select></label><label>الإعلان العام<textarea id="set_ann">'+esc(s.global_announcement||"")+'</textarea></label><button class="primary" onclick="saveSettings()">حفظ الإعدادات</button></div>');$("#set_maint").value=String(!!s.maintenance_mode)}
async function saveSettings(){await api("save_settings",{patch:{maintenance_mode:$("#set_maint").value==="true",global_announcement:$("#set_ann").value}});await load();toast("تم حفظ الإعدادات")}
$("#loginBtn").onclick=async()=>{const msg=$("#loginMsg");msg.textContent="";try{const j=await api("login",{password:$("#password").value});token=j.token;sessionStorage.setItem("pharaoh_admin_token",token);$("#login").classList.add("hidden");$("#app").classList.remove("hidden");await load()}catch(e){msg.textContent=e.message}};
$("#password").addEventListener("keydown",e=>{if(e.key==="Enter")$("#loginBtn").click()});
$("#nav").addEventListener("click",e=>{const b=e.target.closest("button[data-page]");if(!b)return;document.querySelectorAll("#nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPage(b.dataset.page)});
$("#refresh").onclick=async()=>{try{await load();toast("تم تحديث البيانات")}catch(e){if(e.message.includes("الجلسة")){sessionStorage.removeItem("pharaoh_admin_token");location.reload()}else toast(e.message)}};
$("#logout").onclick=async()=>{try{await api("logout")}catch{}sessionStorage.removeItem("pharaoh_admin_token");location.reload()};
if(token){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");load().catch(()=>{sessionStorage.removeItem("pharaoh_admin_token");location.reload()})}