const avatars=['https://i.pravatar.cc/120?img=12','https://i.pravatar.cc/120?img=32','https://i.pravatar.cc/120?img=47','https://i.pravatar.cc/120?img=49','https://i.pravatar.cc/120?img=5','https://i.pravatar.cc/120?img=13'];
const screens={
 splash:{title:'البداية',render:()=>`<section class="screen splash"><div class="orn a"></div><div class="orn b"></div><div class="fade"><div class="brand">صوت يجمعنا</div><div class="sub">غرفة صوتية • أصدقاء • متعة</div><div class="brand-orb" style="margin-top:28px"></div><p class="sub">جاري تحميل التجربة…</p></div></section>`},
 login:{title:'تسجيل الدخول',render:()=>`<section class="screen login"><div class="orn a"></div><div class="login-card fade"><div class="brand-orb"></div><h1>مرحبا بك</h1><p class="sub">سجل دخولك للمتابعة</p><button class="primary">تسجيل الدخول ←</button><button class="secondary" style="margin-top:10px">إنشاء حساب جديد</button><div class="field"><input placeholder="رقم الهاتف"/></div><div class="field"><input placeholder="البريد الإلكتروني"/></div><button class="secondary">🌐 تسجيل عبر Google</button><p style="color:#b56cff">نسيت كلمة المرور؟</p><small class="sub">بالتسجيل أو المتابعة، أنت توافق على الشروط وسياسة الخصوصية</small></div></section>`},
 home:{title:'الرئيسية',render:()=>`<section class="screen"><div class="orn a"></div><header class="top"><div class="user-mini"><img class="avatar" src="${avatars[0]}"><div><b>أمير القلوب</b><div><span class="coin">● 5,250</span> <span class="diamond">◆ 120</span></div></div></div><div><button class="icon-btn">🔔</button><button class="icon-btn">⌕</button></div></header><div class="container"><div class="hero"><h2>غرف صوتية حية</h2><p>اكتشف أفضل الغرف وتحدث مع أشخاص من العالم العربي</p></div><div class="search"><input placeholder="ابحث عن غرفة أو مستخدم…"><button class="icon-btn">⌕</button></div><div class="cats"><span class="cat active">كل الغرف</span><span class="cat">السعودية</span><span class="cat">مصر</span><span class="cat">العراق</span><span class="cat">VIP</span></div><div class="room-grid">${['غرفة النجمة','جلسة طرب','أصدقاء الأبد','غرفة الألعاب'].map((x,i)=>`<article class="room-card"><div class="cover"><span class="live">LIVE</span></div><b>${x}</b><br><small>🇪🇬 ${i+12} متحدث • ${i+2}.1K مستمع</small></article>`).join('')}</div></div><nav class="bottom-nav"><span class="navitem active">⌂<br>الرئيسية</span><span class="navitem">◉<br>الرسائل</span><button class="plus">+</button><span class="navitem">◌<br>الغرف</span><span class="navitem">☰<br>المزيد</span></nav></section>`},
 room:{title:'الغرفة الصوتية',render:()=>`<section class="screen room"><div class="room-head"><div class="room-title">‹ <img class="avatar" src="${avatars[1]}"><div><b>غرفة النجمة</b><small> • 1.2K</small></div></div><div>♛ ⋮</div></div><div class="room-stage"><div class="announcement">مرحباً بكم في غرفة النجمة ✨ — استمتعوا بأجمل الأوقات</div><div class="seats">${avatars.slice(0,4).map((a,i)=>`<div class="seat"><div class="seat-ring ${i===1?'speaking':''}"><img src="${a}"></div><div class="seat-name">${['المالك','سارة','محمد','نور'][i]}</div></div>`).join('')}${avatars.slice(2,6).map((a,i)=>`<div class="seat"><div class="seat-ring"><img src="${a}"></div><div class="seat-name">${['أحمد','فاطمة','Khaled','Yousef'][i]}</div></div>`).join('')}</div></div><div class="room-body"><div class="chat"><div class="msg"><b>أحمد النجم:</b> مرحباً بالجميع 👋</div><div class="msg"><b>سارة:</b> صوت جميل جداً 💜</div><div class="msg">🎁 تم إرسال هدية إلى المالك</div><div class="msg"><b>محمد:</b> أهلاً وسهلاً</div></div><aside class="people"><b>الحضور</b>${avatars.slice(0,5).map((a,i)=>`<div class="person"><img src="${a}"><span>${['أمير القلوب','سارة','محمد','نور','Yousef'][i]}</span></div>`).join('')}</aside></div><div class="room-tools"><div class="tool"><button>🎁</button><br>هدايا</div><div class="tool"><button>💬</button><br>الدردشة</div><div class="tool"><button>🎙️</button><br>الميكروفون</div><div class="tool"><button>↗</button><br>مشاركة</div><div class="tool"><button>🚪</button><br>خروج</div></div></section>`},
 profile:{title:'الملف الشخصي',render:()=>`<section class="screen"><div class="profile-hero"><div class="top">‹ <span>الملف الشخصي</span> ⋮</div><img class="profile-avatar" src="${avatars[0]}"><h2>أمير القلوب ✦</h2><div class="pill" style="display:inline-block">VIP 5</div><p class="sub">ID: 1501637 • 🇪🇬 مصر</p><div class="stats"><div class="stat"><b>245</b><small>متابع</small></div><div class="stat"><b>1.8M</b><small>متابعين</small></div><div class="stat"><b>3.2M</b><small>النقاط</small></div></div><div style="display:flex;gap:8px"><button class="primary">متابعة</button><button class="secondary">مراسلة</button></div></div><div class="container"><div class="section-title"><b>الإنجازات</b><span>عرض الكل</span></div><div class="badge-row"><div class="badge">💎<br>مساعد القلوب</div><div class="badge">👑<br>قائد القمة</div><div class="badge">🏆<br>صانع السعادة</div></div></div></section>`},
 gifts:{title:'الهدايا',render:()=>`<section class="screen"><header class="top">‹ <h3>الهدايا</h3> ♡</header><div class="container"><div class="hero"><b class="coin">● 6,250</b> <span class="diamond">◆ 120</span><p>اختر هدية لإرسالها</p></div><div class="cats"><span class="cat active">كل الهدايا</span><span class="cat">مميزة</span><span class="cat">المفضلة</span></div><div class="gift-grid">${[['🌹','وردة حمراء','100'],['❤️','قلب','20'],['👑','تاج','50'],['🚗','سيارة فاخرة','100'],['✈️','طائرة','200'],['🐉','تنين','500'],['🏰','قصر','1000'],['💐','باقة','2000'],['💎','قطعة ألماس','5000']].map(g=>`<div class="gift"><div class="emoji">${g[0]}</div><b>${g[1]}</b><br><small>● ${g[2]}</small></div>`).join('')}</div><button class="primary" style="margin-top:14px">إرسال هدية 🎁</button></div></section>`},
 messages:{title:'الرسائل',render:()=>`<section class="screen messages"><header class="top"><h3>الرسائل الخاصة</h3><span>⌕</span></header><div class="container"><div class="list">${['سارة','محمد','فاطمة','أحمد','دردشة العائلة','نور','جمال'].map((n,i)=>`<div class="list-row"><div class="user-mini"><img class="avatar" src="${avatars[i%avatars.length]}"><div><b>${n}</b><br><small class="sub">${['ماذا تفعل الآن؟','أرسل لك هدية','أهلاً وسهلاً بك','كيف حالك؟','رسالة جماعية','شكراً لك','تم قبول طلبك'][i]}</small></div></div><small class="sub">${i<2?'09:45':'أمس'}</small></div>`).join('')}</div></div></section>`},
 games:{title:'الألعاب',render:()=>`<section class="screen"><header class="top">‹ <h3>الألعاب</h3>⌄</header><div class="container"><div class="hero"><h2>تحدي الأصدقاء 🎮</h2><p>العب واربح جوائز</p></div><div class="game-grid" style="margin-top:12px">${['🃏 البلوت','🎡 الروليت','🎲 كلمات','♠️ الطاولة','🏆 الفائز','🎯 البحث عن الكنز'].map(x=>`<div class="game">${x}</div>`).join('')}</div></div></section>`},
 settings:{title:'الإعدادات',render:()=>`<section class="screen settings"><header class="top">‹ <h3>الإعدادات</h3></header><div class="container"><div class="list">${['الحساب والخصوصية','الأمان والإشراف','الإشعارات','اللغة — العربية','الصوت والميكروفون','البيانات والتخزين','مساعدة ودعم','الشروط والخصوصية','رقم إصدار التطبيق'].map((x,i)=>`<div class="list-row"><span>${['👤','🛡️','🔔','🌐','🎙️','💾','❓','📄','ℹ️'][i]}</span><b>${x}</b><span style="margin-right:auto">›</span></div>`).join('')}</div></div></section>`},
 vip:{title:'VIP',render:()=>`<section class="screen"><header class="top">‹ <h3>VIP</h3>♡</header><div class="vip-card"><div class="brand-orb"></div><h1>تهانينا!</h1><p>لقد وصلت إلى المستوى الذهبي</p><div class="badge">VIP 5</div><p>مكافآت حصرية • إطار مميز • دخول غرف VIP</p><button class="primary">ممتاز</button></div></section>`},
 recharge:{title:'شحن العملات',render:()=>`<section class="screen recharge"><header class="top">‹ <h3>شحن العملات</h3>⋮</header><div class="container"><div class="hero"><h2>اختر الباقة المناسبة</h2><p>اشحن رصيدك واستخدم العملات للهدايا والعناصر</p></div>${[['50','0.99'],['250','5.99'],['550','9.99'],['1,250','19.99'],['2,750','49.99']].map((p,i)=>`<div class="pack"><span class="diamond">◆ ${p[0]}</span><span>${p[1]} $</span><button class="secondary">اختيار</button></div>`).join('')}<button class="primary">تابع الدفع</button></div></section>`}
};
const PUBLIC_API='https://hgsfdkopbbwbtvsrbpoi.supabase.co/functions/v1/admin-control';
const appData={rooms:[],gifts:[],settings:{}};
async function loadLiveAppData(){
  try{
    const r=await fetch(PUBLIC_API,{method:'POST',headers:{'Content-Type':'application/json','apikey':'sb_publishable_-4jjp6J2GLVPkv8AW95TZQ_DLOEIWOm'},body:JSON.stringify({action:'public_state'})});
    const j=await r.json();
    if(!r.ok) throw new Error(j.error||'تعذر تحميل بيانات التطبيق');
    appData.rooms=j.rooms||[]; appData.gifts=j.gifts||[]; appData.settings=j.settings||{};
  }catch(e){console.warn('Live app data:',e.message)}
}
screens.home.render=()=>`<section class="screen"><div class="orn a"></div><header class="top"><div><b>فرعون بارتي</b><div class="sub">${appData.settings.global_announcement||'غرف صوتية حية'}</div></div><div><button class="icon-btn">🔔</button><button class="icon-btn">⌕</button></div></header><div class="container"><div class="hero"><h2>الغرف الصوتية الحية</h2><p>${appData.rooms.length?'غرف حقيقية قادمة من قاعدة البيانات':'لا توجد غرف حية حالياً'}</p></div><div class="room-grid">${appData.rooms.map(r=>`<article class="room-card" data-room-id="${r.id}"><div class="cover" style="${r.cover_url?'background-image:url('+r.cover_url+')':''}"><span class="live">LIVE</span></div><b>${escApp(r.name)}</b><br><small>${escApp(r.country_code||'')} • ${r.viewer_count||0} مستمع • ${r.seat_count||8} مقاعد</small></article>`).join('')||'<div class="section"><p class="muted">أنشئ غرفة من لوحة التحكم وستظهر هنا تلقائياً.</p></div>'}</div></div><nav class="bottom-nav"><span class="navitem active">⌂<br>الرئيسية</span><span class="navitem">◉<br>الرسائل</span><button class="plus">+</button><span class="navitem">◌<br>الغرف</span><span class="navitem">☰<br>المزيد</span></nav></section>`;
screens.gifts.render=()=>`<section class="screen"><header class="top">‹ <h3>الهدايا</h3> ♡</header><div class="container"><div class="hero"><p>الهدايا الفعالة من قاعدة البيانات</p></div><div class="gift-grid">${appData.gifts.map(g=>`<div class="gift"><div class="emoji">${escApp(g.emoji||'🎁')}</div><b>${escApp(g.name)}</b><br><small>● ${g.coin_price||0} Coins • ◆ ${g.diamond_value||0}</small></div>`).join('')||'<div class="section"><p class="muted">لا توجد هدايا فعالة.</p></div>'}</div></div></section>`;
function escApp(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function getState(){try{return JSON.parse(localStorage.getItem('voice-room-state')||'{}')}catch{return {}}}
function saveState(s){localStorage.setItem('voice-room-state',JSON.stringify(s))}
function applyCustom(html,key){const st=getState();const c=st[key]||{};if(c.text) Object.entries(c.text).forEach(([id,val])=>{html=html.replaceAll(`data-edit="${id}"`,`data-edit="${id}">${val}`)});return html}
function renderScreen(key,target=document.getElementById('app')){const obj=screens[key]||screens.home;target.innerHTML=applyCustom(obj.render(),key)}
const initial=location.pathname.endsWith('editor.html')?'home':'splash'; renderScreen(initial); loadLiveAppData().then(()=>{if(initial==='splash'){setTimeout(()=>renderScreen('home'),500)}else renderScreen(initial)});