let D={},token=localStorage.getItem('royal_admin_token')||'';const $=s=>document.querySelector(s);
const DATA=["config","content","rooms","gifts","categories","events","users","notifications","follows","reports","messages","walletLedger","roomActions"];const LABEL={"config":"الهوية والإعدادات","content":"المحتوى والصفحات","rooms":"الغرف","gifts":"الهدايا","categories":"التصنيفات","events":"الفعاليات","users":"المستخدمون","notifications":"الإشعارات","follows":"المتابعات","reports":"البلاغات","messages":"الرسائل","walletLedger":"سجل المحفظة","roomActions":"إجراءات الغرف"};
async function api(p,o={}){const h={'Content-Type':'application/json',...(o.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch('/api/'+p,{...o,headers:h});return r.json()}
async function boot(){for(const k of DATA)try{D[k]=await api(k)}catch{D[k]=Array.isArray(D[k])?D[k]:{}}if(!token){login();return}tab('overview')}
function login(){const u=prompt('اسم الأدمن','admin'),p=prompt('كلمة المرور');if(!u||!p)return;api('auth/admin/login',{method:'POST',body:JSON.stringify({username:u,password:p})}).then(r=>{if(r.token){token=r.token;localStorage.setItem('royal_admin_token',token);boot()}else alert('بيانات الدخول غير صحيحة')})}
function tab(t){document.querySelectorAll('aside button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));const p=$('#panel');if(t==='overview'){p.innerHTML='<div class="grid">'+['rooms','users','gifts','events'].map(k=>'<div class="card"><b>'+((D[k]||[]).length)+'</b><small>'+LABEL[k]+'</small></div>').join('')+'</div><div class="panel"><h2>مركز التحكم الكامل</h2><p>كل قسم يمكن تعديله وإضافة وحذف عناصره من المحرر. احفظ التغييرات لتظهر في التطبيق.</p><div class="toolbar">'+DATA.map(k=>'<button onclick="tab(\''+k+'\')">'+LABEL[k]+'</button>').join('')+'</div></div>';return}if(DATA.includes(t))editor(t)}
function esc(x){return String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function editor(k){const p=$('#panel'),v=D[k];p.innerHTML='<div class="panel"><h2>'+LABEL[k]+'</h2><div class="toolbar"><button onclick="saveJson(\''+k+'\')">💾 حفظ التعديلات</button><button class="secondary" onclick="addItem(\''+k+'\')">＋ إضافة عنصر</button><button class="secondary" onclick="reload(\''+k+'\')">↻ إعادة تحميل</button><button class="secondary" onclick="tab(\'overview\')">← الرئيسية</button></div><div class="status">لوحة CMS مباشرة • يمكنك تعديل النصوص والروابط والصور والبيانات وإضافة أي حقول جديدة داخل JSON.</div><textarea id="editor" class="editor">'+esc(JSON.stringify(v,null,2))+'</textarea></div>'}
async function saveJson(k){try{const v=JSON.parse($('#editor').value);const r=await api(k,{method:'POST',body:JSON.stringify(v)});if(r.ok){D[k]=v;alert('تم الحفظ وتحديث بيانات التطبيق')}else alert(r.error||'تعذر الحفظ')}catch(e){alert('JSON غير صحيح: '+e.message)}}
function addItem(k){if(!Array.isArray(D[k]))return alert('هذا القسم إعدادات. أضف الحقول من محرر JSON.');D[k].push({id:'new-'+Date.now(),name:'عنصر جديد'});$('#editor').value=JSON.stringify(D[k],null,2)}
async function reload(k){D[k]=await api(k);editor(k)}boot();